name: Minikit
version: 0.0.1
main: dev.sapphicnerd.minikit.Main
description: An experimental plugin
author: sapphicnerddev@github
website: https://github.com/sapphicnerddev/minikit
api-version: '1.21.11'

commands:
  smite:
    description: Lightning!
    usage: /smite <target>
  
  fish:
    description: Summon n fish on the target!
    usage: /fish <target> <num>

  creeper:
    description: Spawns a creeper on the target (optionally charged)
    usage: /creeper <target> <charged>

  sstats:
    description: Display server system info
    usage: /sstats

  jail:
    description: Traps a player in Bedrock for <seconds>
    usage: /jail <target> <seconds>

permissions:
  minikit.smite:
    description: Allows use of /smite
    default: op

  minikit.fish:
    description: Allows use of /fish
    default: op

  minikit.creeper:
    description: Allows use of /creeper
    default: op

  minikit.stats:
    description: Allows use of /sstats
    default: op

  minikit.jail:
    description: Allows use of /jail
    default: op